services:
  - type: web
    name: real-analytics-db
    env: python
    # 构建命令 - 安装依赖
    buildCommand: |
      python -m pip install --upgrade pip
      mkdir -p data/raw data/processed logs
      pip install -r requirements.txt
    # 启动命令 - 包含完整的数据处理流程
    startCommand: |
      # 运行数据抓取和处理
      python -m src.scripts.scrape_rent_estimates
      python -m src.scripts.process_rent_estimates
      python -m src.scripts.import_rent_estimates
      python -m src.scripts.scrape_vacancy_index
      python -m src.scripts.process_vacancy_index
      python -m src.scripts.import_vacancy_index
      python -m src.scripts.scrape_time_on_market
      python -m src.scripts.process_time_on_market
      python -m src.scripts.import_time_on_market
      # Zillow Affordability 数据流程
      python -m src.scripts.scrape_zillow_affordability
      python -m src.scripts.process_zillow_affordability
      python -m src.scripts.import_zillow_affordability
      # 启动调度器
      gunicorn src.scripts.scheduler:app --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        value: 8000
    autoDeploy: true
    healthCheckPath: /health
    healthCheckTimeout: 300
    # 排除测试和检查脚本
    excludeFiles:
      - tests/**/*
      - **/*test*.py
      - **/*_test.py
      - test_*.py
      - pytest.ini
      - .pytest_cache/**/*
      - src/scripts/cleanup_*.py
      - src/scripts/check_*.py
      - src/scripts/verify_*.py
      - src/scripts/drop_*.py
      - data/**/*.csv
      - logs/**/*.log 