services:
  - type: web
    name: real-analytics-db
    env: python
    buildCommand: |
      mkdir -p data
      pip install -r requirements.txt
    startCommand: python -m src.scripts.scheduler
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    autoDeploy: true

  - type: cron
    name: real-analytics-db-update
    schedule: "0 2 * * *"  # 每天凌晨 2 点
    command: curl -X GET https://real-analytics-db.onrender.com/run-update 