services:
  - type: web
    name: real-analytics-db
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      mkdir -p data/raw data/processed logs
      pip install -r requirements.txt
    startCommand: python -m src.scripts.scheduler
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    autoDeploy: true 