services:
  - type: web
    name: real-analytics-db
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      mkdir -p data/raw data/processed logs
      pip install -r requirements.txt
    startCommand: gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        value: 8000
    autoDeploy: true
    excludeFiles:
      - tests/**/*
      - **/*test*.py
      - **/*_test.py
      - test_*.py
      - pytest.ini
      - .pytest_cache/**/*
      - src/scripts/cleanup_*.py
      - src/scripts/check_*.py
      - src/scripts/verify_*.py
      - src/scripts/drop_*.py
      - data/**/*.csv
      - logs/**/*.log 